### ISSUE TITLE
Confusion about the roles of ndPI and nfqueue in nfq_NDPI_firewall

### ISSUE THREAD

**Issue by longpi1** [robingoth/nfq_ndpi_firewall#3]
Hello, I am very interested in this project after reading the documents and papers about nfq_NDPI_firewall project. I hope you can answer me the following questions when you are free.
1. Are there any design documents or articles related to this project that can help me master this project more quickly?
2. Through your introduction of this project, can I understand that NDPI mainly does detection and parsing of network data, and NFQueue does actual filtering, discarding or passing packets?
Looking forward to your reply, thank you very much!

**Comment by fabiodepin** [comment]
Hi,
What is your purpose in using the project to understand your need?

yes, NDPI parses packets to classify them, and nfqueue is able to pipe packets using iptables, but other packet acquisition techniques can be used if desired.

**Comment by longpi1** [comment]
> 嗨， 您使用该项目来了解您的需求的目的是什么？
> 
> 是的，NDPI 解析数据包以对其进行分类，并且 nfqueue 能够使用 iptables 对数据包进行管道传输，但如果需要，可以使用其他数据包获取技术。

**Comment by longpi1** [comment]
> Hi, What is your purpose in using the project to understand your need?
> 
> yes, NDPI parses packets to classify them, and nfqueue is able to pipe packets using iptables, but other packet acquisition techniques can be used if desired.

Thank you very much for your reply, I recently is very interested in the combination of dpi and nfqueue, but it is similar to this project is too little, there is no good learning materials can let me understand dpi implementation details, do you have what good method can let me quickly understand the relevant knowledge of dpi? 
Looking forward to your reply, thank you very much!

**Comment by fabiodepin** [comment]
In a project I did, I used nfqueue to acquire packages, then NDPI for association and identification of applications.
I didn't use connlabel due to kernel limitations with quantity, but you can use libnetfilter to make decisions with verdict.

The base is still in C as you can see in the project I forked (it's outdated), so to make the work easier I integrated/directed the analysis to C++ code passing the null pointer and converting it to the expected type.

It Works very well.
We are currently making modifications to use ipset features directly in the implementation and signal reload handling.
